version: '3'
services :
  nginx :
    image: nginx:1.15
    ports:
      - 80:80
    volumes: 
      - ./source:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes: 
      - ./source:/var/www/html
      # xdebug setting
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    
  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports: 
      - 3306:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql